### ISSUE TITLE
B-bot Autonomous

### ISSUE THREAD

**Issue by minhnguyenbhs** [team401/high-key-2024#16]
**Purpose**
setting up autonomous routines for B-bot

**Project Scope**
- [ ] Recreate paths in PathPlanner
- [ ] Register named commands
- [ ] Drivetrain auto config

**Comment by minhnguyenbhs** [comment]
@jkleiber How much Choreo did we end up using last year?

**Comment by jkleiber** [comment]
closing this in favor of #35
