### ISSUE TITLE
Renaming ____IOInputs to ____Inputs

### ISSUE THREAD

**Issue by minhnguyenbhs** [team401/high-key-2024#19]

**Comment by minhnguyenbhs** [comment]
@jkleiber I was trying to rename all of the files but got this error: what does it mean?
![image](https://github.com/user-attachments/assets/43444165-c8e6-476d-bc4f-f22def1ee602)

**Comment by jkleiber** [comment]
@minhnguyenbhs I don't know what that error is off the top of my head. I assume you could use global find and replace and accomplish the renaming you are trying to do

**Comment by aidnem** [comment]
@minhnguyenbhs you can also select a class name and press F2 (or right-click > rename symbol), and it will automatically rename the class and change the name everywhere it's used in the project as well. That's a huge time save for me when I refactor and rename stuff.
