### ISSUE TITLE
Implement basic Phoenix Pro Swerve Subsystem

### ISSUE THREAD

**Issue by linglejack06** [team401/high-key-2024#2]
- utilize phoenix pro + honzik documentation (update where needed)
- this issue does not involve auto, just basic implementation
- [ ] write subsystem
- [ ] write command to drive subsystem

**Comment by linglejack06** [comment]
@jkleiber could you help me out with the Java issue? At first, wpilib could not find a java vesion 17 jdk, which I have had installed. Now though it builds the java language server will not start up. The icon just spins forever like its loading and I see no log files.

**Comment by linglejack06** [comment]
@jkleiber found wpilib logs this is all it says repeatedly: 
""" 2024-08-22T20:19:00.791Z info: Bad Java version 0 at /Users/jacklingle/wpilib/2024/jdk from JAVA_HOME """

**Comment by jkleiber** [comment]
@linglejack06 my guess would be that you need to set the JAVA_HOME environment variable (looks like wpilib can't find java for some reason).

Is gradle able to build your code from the vscode terminal?

**Comment by linglejack06** [comment]
@jkleiber i figured that too, but my java home variable was already set, so I then reset it following the path to the wpilib location. Gradle works it's just that the extension seems to not find Java. But I have confirmed that Java exists

**Comment by linglejack06** [comment]
I have to run gradle build in vscode terminal which works. The command palette build robot code doesn't work

**Comment by jkleiber** [comment]
@linglejack06 if you haven't restarted your computer since installing wpilib, that is worth a try.

Otherwise I'm not really sure. It sounds like you're doing everything correctly and gradle agrees. The WPILib extension seems to be the problem here. If restart doesn't work, I would try to uninstall WPILib and reinstall in as vanilla a way as possible to give it the best chance of working

**Comment by linglejack06** [comment]
Ok, restarting computer is one thing I haven't tried. I have reinstalled wpilib about seven times though
