### ISSUE TITLE
Rewrite the AimerIO for the actual robot

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#29]
**Purpose**
AimerIORoboRio is defunct. We should be configuring the PID gains for the aimer directly on the Kraken that is driving the arm. This Kraken needs to be configured to accept a CANCoder as an auxillary sensor in order to use that for position feedback.

**Project Scope**
- [ ] Create AimerIO for the robot
- [ ] Configure kraken to use CANCoder as feedback sensor
- [ ] Configure kraken to use PID constants to control arm
- [ ] Add (low) voltage limit and current limit to the arm motor

**Comment by aidnem** [comment]
@jkleiber do you want to run our PID controller on the motor controller or as a WPILib PID controller?

**Comment by jkleiber** [comment]
@aidnem let's try the fused one since we are paying for Phoenix6 anyway lol

**Comment by aidnem** [comment]
Opinions on using Motion Magic? I'm going to implement the IO using Motion Magic but I can swap back to a normal trapezoid profile if needed.

**Comment by jkleiber** [comment]
MotionMagic sounds good, that should just be a trapezoidal profile that runs on the motor controller

**Comment by aidnem** [comment]
I'm not sure how to handle the newProfile parameter for controlAimAngleRad, as I don't think MotionMagic lets you create a new profile as I'm pretty sure it updates on the fly. Can we just remove it and then make sim create a new profile every tick to emulate the on-the-fly behavior of Motion Magic?

**Comment by jkleiber** [comment]
We should just let Motion Magic handle it for the hardware IO - the reason we did that last year was because we were basically doing "we have motion magic at home" on the roboRIO. And yeah updating sim to create a new profile every step sounds good

**Comment by aidnem** [comment]
I'm not sure how to get the current trapezoid setpoint from MotionMagic, which means we can't log a ControlSetpoint and then track how well the PID tuner is following. This could inhibit our ability to tune PID to follow the setpoint if we can't view a graph of the setpoint.

**Comment by aidnem** [comment]
Never mind, after much digging I found getClosedLoopReference()

**Comment by aidnem** [comment]
Dropping [Docs about FeedForward for an arm](https://v6.docs.ctr-electronics.com/en/stable/docs/api-reference/device-specific/talonfx/closed-loop-requests.html#arm-cosine) here for when I inevitably forget how that's supposed to work.
**For this to work properly we have to calibrate the encoder so that 0 is horizontal**

**Comment by PChild** [comment]
The arm reduction is 90:1 overall, you will need this for RotorToSensor ratio.

**Comment by aidnem** [comment]
Thanks so much, I just emailed Oliver to ask lol

**Comment by aidnem** [comment]
I've assume the encoder is a 1:1 with the mechanism. Is this correct?

**Comment by PChild** [comment]
Yes, it is

**Comment by aidnem** [comment]
@jkleiber mostly done rewriting the aimer IO (I have to test it at home because I can't build the project in a github codespace). I can't find a way to apply a voltage limit when we're using closed-loop running on the TalonFX. Can we just tune with very very low gains and hope it doesn't destroy itself?

**Comment by jkleiber** [comment]
@aidnem I'm seeing the issue as well. We can make the current limit really low and if we understand the units we can set the gains to be low at first and hopefully be fine

**Comment by jkleiber** [comment]
Also - we should make the velocity and acceleration quite low for motion magic initially. Then once we are confident the motor will drive the correct direction, we can start opening up the limits

**Comment by aidnem** [comment]
@jkleiber do you want me to try and add the ability to tune PID through elastic if I have time?

**Comment by jkleiber** [comment]
Yeah that will be helpful. We only need it in test mode if that helps

**Comment by aidnem** [comment]
I don't know if test mode exists as of yet, I'm going to try to just add what I need and see what happens.
