### ISSUE TITLE
Ensure ShooterIO is correct for robot hardware and tune shooter PID

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#31]
**Purpose**
The purpose of this ticket is to ensure the shooter flywheels are ready to go for integration on **Wednesday October 9th**

This is only for the shooter flywheels, not the aimer. the aimer is being worked in #29 

We need to make sure the shooter IO is actually correct for the real robot hardware. Additionally, we need a way to tune the PID gains in shop. This ticket will also be used to tune the shooter

**Project Scope**
- [x] Ensure shooter IO is correct for B bot
- [x] Update code as needed to make gains tunable

**Comment by jkleiber** [comment]
@minhnguyenbhs can you have this ready by tomorrow?

**Comment by minhnguyenbhs** [comment]
@jkleiber The flywheels were running when we had the arm last week and I've hopefully fixed the kicker vs. intake motor error, although I can check that later today! should I add SmartDashboard widgets for editing gains?

**Comment by jkleiber** [comment]
@minhnguyenbhs Adding smartdashboard/elastic widgets for tuning gains in test mode would be great! If we have code that works with the flywheels, is that in main or in a branch? If it is in a branch, let's just make sure that branch is updated and ready to go on Wednesday so we can get the gains tuned and knock out this integration task

**Comment by minhnguyenbhs** [comment]
@jkleiber Got it, thank you! 
All of the hardware is in the shooter hardware branch. I think the only thing that isn't currently updated is motor ids- do you know what they are? Thank you!

**Comment by jkleiber** [comment]
@PChild has documented the motor IDs for most of the motors here: https://github.com/team401/high-key-2024/discussions/26

I assume the shooter flywheels are whatever ID they were when you got them running in shop last week.
