### ISSUE TITLE
Add LED indicators for drivers

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#36]
**Purpose**
The purpose of this addition is to add LED indications for the following:
1. If the beelink is off
2. If a note is in the arm vs the shooter vs not at all

**Project Scope**
- [ ] Add LED display for beelink off
- [ ] add LED display for note detection

**Comment by aidnem** [comment]
@avidraccoon what's the status on this?
Also, Oliver requested that we make the LEDs turn red for a few seconds at the start of endgame. Could you add this?

**Comment by jkleiber** [comment]
It looks like there's a branch, could we make a draft PR for it so the work is more visible?

**Comment by aidnem** [comment]
👍 Created #69

**Comment by aidnem** [comment]
@PChild https://github.com/user-attachments/assets/09f51dc5-ebaf-4e19-af51-0af064d9569d

**Comment by PChild** [comment]
Thank you Aiden, very cool!
