### ISSUE TITLE
Add USB drive to roboRIO for swap memory

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#37]
**Purpose**
On October 7th 2024, we observed that the roboRIO ran out of RAM with only the drive and intake subsystems enabled. This is a roboRIO 1, so it has limited RAM.

The objective of this ticket is to install and configure a USB drive to be used as swap memory on the RIO. This should sufficiently mitigate our memory issues for offseason competitions

**Project Scope**
- [x] Add USB drive to roboRIO
- [ ] Configure drive to be used as swap memory

**Comment by aidnem** [comment]
Docs for that can be found [here](https://docs.wpilib.org/en/stable/docs/software/basic-programming/java-gc.html#setting-up-swap-on-a-usb-flash-drive).

**Comment by PChild** [comment]
I did not do swap space but installed a USB drive for logs to save to. I did disable the web server and swap lvrt to the shell script. We're no  longer getting code crashes, free disk is around 55 MB, free ram around 77 MB.

**Comment by jkleiber** [comment]
77MB is a good amount of RAM, I hope we can avoid using all of it

**Comment by jkleiber** [comment]
I'm going to close this for now since we didn't see issues on Wednesday. If we run into problems again we can reopen this or create a new issue
