### ISSUE TITLE
Implement Shooter

### ISSUE THREAD

**Issue by minhnguyenbhs** [team401/high-key-2024#4]
**Summary:**
Write code for shooter

- [ ] make sim vs talon io
- [ ] motor for taking handoff from intake
- [ ] 2 motors for shooting (note: original robot varies flywheel speed by side for spin?)
- [ ] motor for adjusting angle of pendulum
- [ ] combine all motors for different launching distances? (combine w vision)

**Comment by minhnguyenbhs** [comment]
@jkleiber I'm currently unable to figure out why the math and controls files in coppercore aren't working; I'm postponing working on coppercore until after simulating intake, so I probably won't get to it for a while, but do you have some ideas on what could maybe be causing the library to not work? wpilib_interface is functional, which is a bit odd? Thank you!

**Comment by jkleiber** [comment]
@minhnguyenbhs do you have any error messages / a minimal reproduceable example?

**Comment by minhnguyenbhs** [comment]
I think it is just reporting a typical library "does not exist" error?

Thank you so much for your help!

> Task :compileJava
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:23: error: package coppercore.controls does not exist
import coppercore.controls.Tunable;
                          ^
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:27: error: package coppercore.math does not exist
import coppercore.math.InterpolateDouble;
                      ^
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:29: error: cannot find symbol
public class ScoringSubsystem extends SubsystemBase implements Tunable {
                                                               ^
  symbol: class Tunable
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:46: error: cannot find symbol
    private final InterpolateDouble shooterInterpolated;
                  ^
  symbol:   class InterpolateDouble
  location: class ScoringSubsystem
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:47: error: cannot find symbol
    private final InterpolateDouble aimerInterpolated;
                  ^
  symbol:   class InterpolateDouble
  location: class ScoringSubsystem
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:48: error: cannot find symbol
    private final InterpolateDouble timeToPutAimDown;
                  ^
  symbol:   class InterpolateDouble
  location: class ScoringSubsystem
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:49: error: cannot find symbol
    private final InterpolateDouble aimerAvoidElevator;
                  ^
  symbol:   class InterpolateDouble
  location: class ScoringSubsystem
C:\Users\LabUser\Documents\high-key-2024\src\main\java\frc\robot\subsystems\scoring\ScoringSubsystem.java:50: error: cannot find symbol
    private final InterpolateDouble aimerAngleTolerance;
                  ^
  symbol:   class InterpolateDouble
  location: class ScoringSubsystem

**Comment by jkleiber** [comment]
@minhnguyenbhs it looks like the build.gradle for the coppercore controls library is in the wrong directory. I'm going to take a closer look at the math library since that seems to have the build.gradle in the right location

**Comment by jkleiber** [comment]
@minhnguyenbhs I think I see the problem. In java, the package needs to be declared at the top of the file, i.e.

`package coppercore.controls;` needs to be added to the top of Tunable.java, and `package coppercore.math;` needs to be added to the top of InterpolateDouble.java.

Hopefully that will get these things packaged correctly (also moving the build.gradle for controls should help)

**Comment by minhnguyenbhs** [comment]
I think coppercore is working now- thank you so much for your help!
