### ISSUE TITLE
Pose Supplier Never Updated?

### ISSUE THREAD

**Issue by PChild** [team401/high-key-2024#43]
https://github.com/team401/high-key-2024/blob/6498fb50cea600d2f234005e3479dcf91cc0fe59/src/main/java/frc/robot/subsystems/scoring/ScoringSubsystem.java#L381

We started trying to do shooter lookups and it seems like this pose is never updated, `distance` on the dashboard always says zero so we always get sent to the angle corresponding to zero in the hashmap.

**Comment by linglejack06** [comment]
@PChild i looked through the code, and a pose supplier is never set for the scoring subsystem (unless i'm missing something). This should be done from the robot container with the pose supplied by the drive. @jkleiber do you want me to make a new branch and add this or put this in a branch already created?

**Comment by jkleiber** [comment]
@linglejack06 let's update the 14-calibrate-cameras branch since that's what I think @aidnem was working off of

**Comment by jkleiber** [comment]
Alternatively if that branch gets merged we can work this separately

**Comment by linglejack06** [comment]
@jkleiber ive added a pose supplier in the initScoring method. Also, I noticed that in initIntake, it is assumed that scoring exists, but if we have runScoring off wont that causes an issue? Specifically this code block: 
``` 
        BooleanSupplier shooterHasNote =
                () -> {
                    return scoringSubsystem.hasNote();
                };
        BooleanSupplier shooterInIntakePosition =
                () -> {
                    return scoringSubsystem.aimerAtIntakePosition();
                };
        intakeSubsystem.setShooterHasNoteSupplier(shooterHasNote);
        intakeSubsystem.setShooterAtIntakePosition(shooterInIntakePosition);
```

should we add a basic null check and then if null just return false? Or will this work how it is?

**Comment by linglejack06** [comment]
@jkleiber ive added the configureSuppliers method. Also I noticed that configure modes is called twice, should one be removed I assume?

**Comment by jkleiber** [comment]
Yeah let's call that only one time

**Comment by linglejack06** [comment]
does it matter if we call it at the end of init or is it fine to go in the
middle there? right now its subsystems -> suppliers -> modes -> bindings ->
modes

**Comment by jkleiber** [comment]
@linglejack06 it makes the most sense to me to put it at the end
