### ISSUE TITLE
Set aimer voltage to 0 when near the hard stop

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#45]
**Purpose**
The purpose of this ticket is to allow the aimer to rest against the hard stop when in intake/idle modes rather than using the PID to hold it up.

**Project Scope**
- [ ] Set aimer voltage to 0 when near the hard stop and in either the intake or idle state (this probably involves turning motion magic off when in this control regime)
- [ ] Test on the robot

**Comment by aidnem** [comment]
@minhnguyenbhs 2 comments/suggestions here:
A (less important): we could consider not instantiating a new motion magic request every loop (line 232), I'm not sure if this will cause lag but maybe it would be better not to do it.
B (more important): you don't need to explicitly turn off the motion magic request, sending a VoltageOut(0.0) request or calling setVoltage(0.0) (hopefully) should be enough to stop it without explicitly cancelling the motion magic request. Not sure on this though as I've never tested override mode.

**Comment by minhnguyenbhs** [comment]
I made some really minor edits that essentially cancel motionmagic when the goal angle is less than the aimer minimum angle + tolerance. Should that work? I'll test it at shop

Also, is goalAngleRad in radians or rotations?

**Comment by jkleiber** [comment]
Seems legit @minhnguyenbhs . Despite all the variable names suggesting radians, everything is in rotations now for aimer

**Comment by aidnem** [comment]
@jkleiber can motors move while a config is being applied? If it tries to apply the normal config again after starting to aim this could delay aiming for shots.

**Comment by jkleiber** [comment]
That's a fair point - what do the docs say?

If the motor can't move while configs are applied, then we probably just need to find the voltage that keeps the arm down but doesn't go above some amount of amps. Then we'd just leave the current limit as is

**Comment by minhnguyenbhs** [comment]
There's an apply method that we aren't using that has a timeoutSeconds specifically to have the motor wait when performing configurations to check for errors. The default number is 0.050 seconds, so I think the motor will wait for 0.050 seconds to run per config- should I get rid of the current limit setting for the negative voltage lock, then?
