### ISSUE TITLE
Try RemoteCANCoder in place of FusedCANCoder

### ISSUE THREAD

**Issue by aidnem** [team401/high-key-2024#52]
**Purpose**
High key struggled with incorrect aimer encoder values at BRB. To confirm that this isn't caused by a problem with our FusedCANCoder configuration, we should try using just the CANCoder without the Kraken's internal encoder potentially messing stuff up.
[Phoenix6's TalonFX docs for remote sensors can be found here](https://v6.docs.ctr-electronics.com/en/stable/docs/api-reference/device-specific/talonfx/remote-sensors.html)

**Project Scope**
- [ ] Add code to AimerIORoboRio to use CANCoder only.
- [ ] Test it to to see if it is more reliable than using FusedCANCoder.
- [ ] If RemoteCANCoder is better, make a lower-priority ticket to do some digging to figure out why our FusedCANCoder code doesn't work, as there's no real reason we shouldn't be able to use it.

**Comment by aidnem** [comment]
@jkleiber I'm considering keeping the FusedCANCoder code in place as well, and using a ScoringConstant to toggle between the two. This way, we could alternate between the two (and maybe add a third mode for motor encoder only if we ever decide to go the other direction and fully ignore the CANCoder). Thoughts?

**Comment by PChild** [comment]
Please do not spend time on this, I'm pretty confident that all of the Fused issues were mechanical and not code, we have a plan to fix the mechanics of this already. If we were to go to any new control strategy I think motor encoder only is a better option.

**Comment by jkleiber** [comment]
This is a fairly low priority task that wouldn't take much time to implement if we need to do it. We should leave the ticket open for now in case we rule out mechanical issues being the root cause of the encoder problems

**Comment by aidnem** [comment]
I deleted the branch to avoid clutter but we can always come back to this if needed.

**Comment by aidnem** [comment]
Aimer is working beautifully now that the encoder isn't broken, I think this is unnecessary.
