### ISSUE TITLE
Create and tune a pass shot

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#55]
**Purpose**
The purpose of this ticket is to add a mode where we can pass notes from midfield to the wing 

Less angular accuracy is required for this shot but we do want the notes to land near our own amp. We will need to be able to shoot over the stage to do this

This ticket is where we will also tune the shot

**Project Scope**
- [ ] Add pass shot ability
- [ ] tune pass shot to work

**Comment by aidnem** [comment]
@jkleiber does this need to shoot to near the amp, or would it be okay to just use speaker alignment and slightly decrease shooter rpm to shoot near speaker

**Comment by jkleiber** [comment]
@aidnem I talked to @linglejack06 and we agreed to basically aim sort of near the corner and shoot at some RPM+angle. We'll need to test this on Wednesday
