### ISSUE TITLE
Add music to robot

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#67]
**Purpose**
Phoenix 6 has support for playing music: https://v6.docs.ctr-electronics.com/en/latest/docs/api-reference/api-usage/orchestra.html

The songs can be played during disabled mode as a sort of walk-up music, and can also be played during a match. For example you could add a sound effect for scoring a note or picking up a note. We could also have a song play while we are waiting for a match to start

You can convert pretty much any MIDI file to CHRP (the format needed by Phoenix 6) in TunerX. If you want to do something fun on the bus ride to comp, we will absolutely test this in the pits and try to get it working at Rumble.

The only requirements of this ticket:
- Any songs need to be appropriate for an FRC event
- We need a way to feature flag this on Elastic so we can have a quiet pit when needed

**Project Scope**
- [ ] Add whatever songs and sound effects you want
- [ ] Implement Orchestra to play sounds during different moments in the game
- [ ] Add ability to disable the feature / toggle music on/off in Elastic

**Comment by PChild** [comment]
Some song suggestions:

- [Danger Zone](https://onlinesequencer.net/140813)
- [Sweet Victory](https://onlinesequencer.net/37671)
- [Enter Sandman](https://onlinesequencer.net/2071082)
- [Megalovania](https://onlinesequencer.net/256345)
- [Mii channel theme](https://onlinesequencer.net/810035)
- [Jeopardy music](https://onlinesequencer.net/58022)

**Comment by aidnem** [comment]
I suggest mii channel theme for disabled, megalovania for auto, the final countdown for the last 20 seconds of the match.

**Comment by avidraccoon** [comment]
Should I make it controlled by JSON?

**Comment by aidnem** [comment]
Do we have JSON working on this robot yet? I don't want to introduce code crashes by adding music.

**Comment by avidraccoon** [comment]
> Do we have JSON working on this robot yet? I don't want to introduce code crashes by adding music.

I already have json working, just do not have the files to load json from for it, and I have tested the json on c bot before so I don't believe it should cause any problems.

**Comment by aidnem** [comment]
Sure, add in JSON to describe what songs to play in each mode. For instance, we could do like
```json
{
    "disabled": "wii_shop.chrp",
    "auto": "megalovania.chrp",
    "endgame": "final_countdown.chrp",
}
```
If you want to write that, I can add the music stuff to the IOs and add elastic bindings for it (unless you really want to).

**Comment by jkleiber** [comment]
You could configure which songs are for which phase of the match by adding JSON. Could be a good opportunity to give the JSON parsing logic a small role before relying on it for critical things.

We should ensure that any JSON-related failure leaves the robot in an operating state for this feature since it is non critical.

We're going to keep this in a branch until it's tested and verified so I'm not worried about regressions.

**Comment by avidraccoon** [comment]
Yeah I will make sure to make it so it can fail without messing up the robot

**Comment by aidnem** [comment]
Also it looks like the orchestra object will handle errors and return them to you rather than crashing code anyway, so that will be safe if we put the wrong filename in as well.

**Comment by aidnem** [comment]
@avidraccoon I already created a branch as I thought I'd be writing this so you can go ahead and use that to add the JSON stuff :)

**Comment by avidraccoon** [comment]
Aiden if you can write the music to IOs I can work on setup json for it

**Comment by aidnem** [comment]
Bet. I'll add that to the IOs and then it's yours to play with JSON.

**Comment by avidraccoon** [comment]
How does this look
```json
{
   "songs" : [
      "mii": "music/mii.chrp",
      "final-count-down": "music/final_count_down.chrp",
      "megalovania": "music/megalovania.chrp"
   ],
   "states" : [
      "disabled": "mii",
      "auto": "megalovania",
      "endgame": "final-count-down"
   ],
   "events" : [
   
   ]
}
```

**Comment by aidnem** [comment]
Looks fine, but do we really need to map the names of songs to filenames instead of just using the filenames directly? Seems like it just introduces more opportunities for typos and you can only load 1 file at a time into the Orchestra object anyway.

**Comment by aidnem** [comment]
@jkleiber should I add a subsystem that takes getters from every TalonFX motor on the robot to play all of the music in sync, or do we just want to pick one motor and have it play all of our music? If the latter, which motor?

**Comment by avidraccoon** [comment]
> Looks fine, but do we really need to map the names of songs to filenames instead of just using the filenames directly? Seems like it just introduces more opportunities for typos and you can only load 1 file at a time into the Orchestra object anyway.

Is this better?
~~~json
{
   "states" : [
      "disabled": "music/mii.chrp",
      "auto": "music/megalovania.chrp",
      "endgame": "music/final_count_down.chrp"
   ],
   "events" : [
   
   ]
}
~~~

**Comment by aidnem** [comment]
Yeah that looks better to me. Let me know if you think my logic is flawed by the way, my word isn't law. Also, we should add the zelda guardian charge-up music for priming states.

**Comment by avidraccoon** [comment]
> Yeah that looks better to me. Let me know if you think my logic is flawed by the way, my word isn't law. Also, we should add the zelda guardian charge-up music for priming states.

Could you give a link to that audio please?

**Comment by PChild** [comment]
I don't think motors can do music and move at the same time, maybe we don't use this during match, just in disabled.

**Comment by aidnem** [comment]
Hear me out we get like 4 krakens and slap them on the back of the robot and all they do is play music /J

**Comment by avidraccoon** [comment]
We might be able to set it up so that it could use any unused motors and pause or just not play if there are no available motors

**Comment by PChild** [comment]
I don't think motors can do music and move at the same time, maybe we don't use this during match, just in disabled.

**Comment by jkleiber** [comment]
@aidnem we want to be as loud as possible so playing on all motors in disabled is preferred

**Comment by aidnem** [comment]
@avidraccoon orchestra code is written. You can replace the defaultMusic being hardcoded with a JSON reader, as that's the only thing I could think of being configurable since we are only playing in disabled.

@jkleiber I also made it so that we can change the file it's playing with smart dashboard/elastic and pause or play the music.

**Comment by jkleiber** [comment]
Nice, looking forward to this on Saturday

**Comment by aidnem** [comment]
@jkleiber any idea if manually instantiating TalonFXs using the same motor IDs from swerve and then applying an audio config to them will disrupt drive? If it fails it'll probably be a CAN error (duplicate IDs). I'm not sure how to extract the talonFXs from the drive subsystem otherwise.

**Comment by aidnem** [comment]
I'm going to dig around in the API documentation tomorrow and see if I can get a reference to the actual TalonFX object for each swerve motor because that's 8 more motors we can use to play music.

**Comment by avidraccoon** [comment]
I belive the TalonFx extends CoreTalon which extends ParentDevice so shouldn't the talonfx object work?

**Comment by avidraccoon** [comment]
It's possible  by calling getModules on the SwerveDriveTrain returning SwerveModule[] and then calling getDriveMotor() and getSteerMotor() returning two TalonFX

**Comment by aidnem** [comment]
Awesome, thank you.
